### ISSUE TITLE
Configuration of CMake

### ISSUE THREAD

**Issue by ralf307** [HeYijia/stereo_elas#2]
你好！

我在cmake的时候出现了如下错误，想请问如何解决。是不是需要改build -> CMakeCache.txt里面的某些路径呢？多谢！

C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\GAOXIA\CMakeBuilds\c7b7ea34-c7b3-d83a-8fe5-ac32664de015\install\x64-Debug (Standard)"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\HUD-Aufbau\stereo_elas-master" wurde mit Exitcode zurückgegeben: 1
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.
  Could not find a package configuration file provided by "OpenCV" (requested
  version 2.4) with any of the following names:
    OpenCVConfig.cmake
    opencv-config.cmake
  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by HeYijia** [comment]
应该是你电脑装的是 opencv3, 但是我在 CMakeLists.txt 的 19 行写的是 find_package(OpenCV 2.4 REQUIRED)，也就是找的是 opencv 2.4, 你可以把 2.4 去掉再编译。

**Comment by ralf307** [comment]
多谢回复啊。我把2.4去掉了但还是没有编译成功... 我电脑上是OpenCV 4，在Visual Studio 2017上试过是可以的
